name: Build Geode Mod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Clone Geode SDK
        shell: pwsh
        run: |
          git clone https://github.com/geode-sdk/geode.git --recursive --depth 1 -b v5.4.1 "${{ runner.temp }}\geode-sdk"

      - name: Configure
        shell: pwsh
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo
        env:
          GEODE_SDK: ${{ runner.temp }}\geode-sdk

      - name: Build
        shell: pwsh
        run: |
          cmake --build build --config RelWithDebInfo
        env:
          GEODE_SDK: ${{ runner.temp }}\geode-sdk

      - name: Find geode file
        shell: pwsh
        run: |
          Get-ChildItem -Recurse -Filter "*.geode" | ForEach-Object { Write-Host $_.FullName }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: music-downloader
          path: |
            build/**/*.geode
            **/*.geode
